In [2]:

# # NumPy 30秒快速練習題
# 這些練習題設計用於快速驗證 NumPy 的核心概念理解，每題應該能在 30 秒內想出解法。

import numpy as np
import matplotlib.pyplot as plt


## M1: ndarray 基礎

In [3]:
# 練習 1.1: 基本陣列建立
# 任務：建立一個包含 1-5 的一維陣列
# 提示：使用 np.array()
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [8]:
# 練習 1.2: 陣列屬性檢查
# 任務：建立一個 2x3 陣列，並檢查其維度、形狀和數據類型
# 提示：使用 .ndim, .shape, .dtype
arr2 = np.array([[1, 2, 3, 4, 5, 6]]).reshape(2, 3)
arr2.shape

(2, 3)

In [9]:
# 練習 1.3: 簡單運算
# 任務：將陣列 [1, 2, 3, 4, 5] 中的所有元素乘 2
# 提示：使用陣列乘法
arr3 = np.array([1, 2, 3, 4, 5]) * 2
arr3

array([ 2,  4,  6,  8, 10])


## M2: 陣列建立方式

In [10]:
# 練習 2.1: 特殊陣列
# 任務：建立一個 3x3 的單位矩陣
# 提示：使用 np.eye()
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# 練習 2.2: 等差數列
# 任務：建立 0 到 10 間隔為 2 的陣列
# 提示：使用 np.arange()
sequence = np.arange(0, 11 ,2)
sequence

array([ 0,  2,  4,  6,  8, 10])

In [14]:
# 練習 2.3: 隨機數陣列
# 任務：生成 5 個 0-1 之間的隨機數
# 提示：使用 np.random.rand()
random_array = np.random.rand(5)
random_array

array([0.33518937, 0.42402974, 0.81930654, 0.19917156, 0.98790851])


## M3: 索引與切片

In [16]:
# 練習 3.1: 基本切片
# 任務：從陣列 [1, 2, 3, 4, 5] 中取出前三個元素
arr = np.array([1, 2, 3, 4, 5])
first_three = arr[:3]
first_three

array([1, 2, 3])

In [17]:
# 練習 3.2: 條件索引
# 任務：找出陣列 [2, 4, 6, 8, 10] 中大於 5 的元素
arr = np.array([2, 4, 6, 8, 10])
greater_than_five = arr > 5
arr[greater_than_five]

array([ 6,  8, 10])

In [20]:
# 練習 3.3: 二維切片
# 任務：從 2x3 矩陣中取出第一列
arr = np.array([[1, 2, 3], [4, 5, 6]])
first_row = arr[0:1, :]
first_row

array([[1, 2, 3]])


## M4: Broadcasting

In [19]:
# 練習 4.1: 標量廣播
# 任務：將陣列 [1, 2, 3] 中的每個元素加 5
arr = np.array([1, 2, 3])
result1 = arr + 5
result1

array([6, 7, 8])

In [21]:
# 練習 4.2: 一維廣播
# 任務：將向量 [10, 20, 30] 加到矩陣的每一列
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([10, 20, 30])
result2 = matrix + vector
result2

array([[11, 22, 33],
       [14, 25, 36]])

In [23]:
# 練習 4.3: 形狀擴展
# 任務：將一維陣列 [1, 2, 3] 轉為列向量（3x1 矩陣）
arr = np.array([1, 2, 3])
col_vector = arr.reshape(3, 1)
col_vector

array([[1],
       [2],
       [3]])


## M5: 數學函數

In [26]:
# 練習 5.1: 基本數學運算
# 任務：計算陣列 [1, 4, 9, 16] 的平方根
arr = np.array([1, 4, 9, 16])
sqrt_result = np.sqrt(arr)
sqrt_result

array([1., 2., 3., 4.])

In [28]:
# 練習 5.2: 統計函數
# 任務：計算陣列 [1, 2, 3, 4, 5] 的平均值和標準差
arr = np.array([1, 2, 3, 4, 5])
mean = np.mean(arr)
std = np.std(arr)
std

np.float64(1.4142135623730951)

In [30]:
# 練習 5.3: 三角函數
# 任務：計算角度 [0, π/2, π] 的正弦值
angles = np.array([0, np.pi/2, np.pi])
sin_values = np.sin(angles)
sin_values

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])


## M6: 統計分析應用

In [31]:
# 練習 6.1: 數據標準化
# 任務：將數據 [1, 2, 3, 4, 5] 標準化（減均值除以標準差）
data = np.array([1, 2, 3, 4, 5])
standardized = (data - np.mean(data)) / np.std(data)
standardized

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [33]:
# 練習 6.2: 相關係數
# 任務：計算兩組數據的相關係數
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 4, 5])
correlation = np.corrcoef(x, y)[0, 1]
correlation

np.float64(0.7745966692414834)

In [ ]:
# 練習 6.3: 簡單統計描述
# 任務：計算數據 [1, 2, 3, 4, 5] 的基本統計量（平均值、中位數、標準差、最小值、最大值）
data = np.array([1, 2, 3, 4, 5])
stats = None